version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
  jobs:
    post_create_environment:
      - cp -a locale sphinx/doc/

submodules:
  include: all
  
formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
