version: 2
sphinx:
  configuration: sphinx/doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
  jobs:
    post_create_environment:
      - cp -a locales sphinx/doc/
    install:
      - pip install --upgrade pip
      - pip install --group sphinx/pyproject.toml:docs

submodules:
  include: all
