version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # install requirements
    - pip install -r requirements.txt
    - apt install -y graphviz
    # initialise submodule (https://github.com/sphinx-doc/sphinx.git)
    - git submodule init
    - git submodule update
    # run Sphinx
    - >
      sphinx-build ./sphinx/doc/ ./_readthedocs/html 
      -b html  
      -D locale_dirs=$(realpath locale)
      -D language=$(python convert_language_tag.py)
      -D gettext_compact=0
