version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
  jobs:
    post_create_environment:
      - git clone https://github.com/sphinx-docs/sphinx ../sphinx
      - cp -A locale ../sphinx/doc/

sphinx:
  builder: html
  configuration: ../sphinx/doc/conf.py
  fail_on_warning: true
