version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # install requirements
    - pip install -r requirements.txt
    # initialise submodule (https://github.com/sphinx-doc/sphinx.git)
    - git submodule init
    - git submodule update
    # rename locale to meet $READTHEDOCS_LANGUAGE
    - (cd locale; for dir in $(ls -d * | grep _[A-Z]); do renamed=$(echo $dir | tr '_' '-' | tr [:upper:] [:lower:]); mv $dir $renamed; done;)
    # run Sphinx
    - >
      sphinx-build ./sphinx/doc/ ./_readthedocs/html 
      -b html  
      -D locale_dirs=$(realpath locale)
      -D language=$READTHEDOCS_LANGUAGE
      -D gettext_compact=0
