version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
  jobs:
    post_create_environment:
      - git clone https://github.com/sphinx-doc/sphinx sphinx
      - cp -a locale sphinx/doc/

python:
  install:
    - requirements: requirements.txt
